### ISSUE TITLE
Unable to Complete Account Recovery Process,  button doesn't show up

### ISSUE THREAD

**Issue by zach-pagel** [diodechain/diode_drive_feedback#84]
Software Details
--
**OS:**  Linux Linux 5.8.0-53-generic x86_64
**Distro:** Ubuntu 20.04 LTS
**Diode Drive Launcher Build:** 1.2.0
**Diode Drive Base Version:**  1.2.1
**Diode Drive Patch Level:** v1.2.1-1-gb7d8ebc

Description
--
**Problem:** Unable to complete account recovery process after typing in backup code. Cannot advance to next step/screen.

**Steps to Reproduce**
1. Launch Diode Drive
2. Type in existing Diode Drive account name in the "Choose an Account Name" box
3. Click the "Log In" button
4. Type in backup code for the Diode Drive account name

**Screenshot**
![image](https://user-images.githubusercontent.com/17348062/118881753-078be000-b8b9-11eb-8cd8-3e84630b4f29.png)

**Comment by zach-pagel** [comment]
On Windows 10, clicking the enter key advances the process and logs the user in successfully.

**Comment by hansr** [comment]
Verified this is an issue in MacOS as well.

@fayddelight

**Comment by fayddelight** [comment]
Fixed.

**Comment by zach-pagel** [comment]
I still can't advance past the screen shown in the screenshot above with the latest Diode Drive build on Ubuntu 20.04 LTS.
